function exportReconToExcel(recon, filename)
% exportReconToExcel  Recon yapısındaki verileri Excel dosyasına kaydeder.
%
%   exportReconToExcel(recon, filename)
%
% recon   : recon yapısı
% filename: Yazılacak Excel dosyasının adı (örn. 'recon_data.xlsx')
%
% Fonksiyon, bilgileri farklı sayfalara (sheet) yazacaktır.

    %% 1. Parameters sayfası: Temel parametreler
    params = table(recon.tol, recon.max_itr, recon.noise_std, recon.noise_rms, ...
        recon.SNR_dB, recon.num_lambda, recon.iso_value, ...
        'VariableNames', {'tol','max_itr','noise_std','noise_rms','SNR_dB','num_lambda','iso_value'});
    writetable(params, filename, 'Sheet', 'Parameters');
    
    %% 2. OptimumLambda sayfası: Seçilen optimum lambda değerleri
    optLambda = table( ...
        recon.opt_lambda_LC_case1, recon.opt_lambda_LC_case2, ...
        recon.opt_lambda_GCV_case1, recon.opt_lambda_GCV_case2, ...
        recon.opt_lambda_Morozov_case2, ...
        recon.opt_lambda_triangle_ideal, recon.opt_lambda_triangle_noisy, ...
        recon.opt_lambda_corner_ideal, recon.opt_lambda_corner_noisy, ...
        recon.opt_lambda_UC_ideal, recon.opt_lambda_UC_noisy, ...
        'VariableNames', {'LC_Ideal','LC_Noisy','GCV_Ideal','GCV_Noisy',...
                           'Morozov_Noisy','Triangle_Ideal','Triangle_Noisy',...
                           'Corner_Ideal','Corner_Noisy','UC_Ideal','UC_Noisy'});
    writetable(optLambda, filename, 'Sheet', 'OptimumLambda');
    
    %% 3. Metrics sayfası: Hata metrikleri
    if isfield(recon, 'nssd_array') && isfield(recon, 'nsad_array') && isfield(recon, 'nr_array')
        methods = {'LC'; 'GCV'; 'Morozov'; 'Triangle'; 'Corner'; 'UC'};
        metrics = table(methods, recon.nssd_array, recon.nsad_array, recon.nr_array, ...
            recon.volErrVoxel_array, recon.volErrMM_array, ...
            recon.centErrVoxel_array, recon.centErrMM_array, ...
            'VariableNames', {'Method','NSSD','NSAD','NR','VolumeErrorVoxels','VolumeErrorMM3','CentroidErrorVoxels','CentroidErrorMM'});
        writetable(metrics, filename, 'Sheet', 'Metrics');
    end
    
    %% 4. LambdaRange sayfası: lambda_range dizisinin özetlenmiş hali
    lambdaRange = table((1:length(recon.lambda_range))', recon.lambda_range(:), ...
        'VariableNames', {'Index','Lambda'});
    writetable(lambdaRange, filename, 'Sheet', 'LambdaRange');
    
    fprintf('Recon verileri Excel dosyasına aktarıldı: %s\n', filename);
end
